routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', [\App\Http\Controllers\NewsController::class, 'index']);

Route::resource('news', \App\Http\Controllers\NewsController::class);

Route::post('ratings', [\App\Http\Controllers\RatingController::class, 'store'])
    ->name('rating.store')
    ->middleware('auth');

Route::resource('news.comments', \App\Http\Controllers\CommentsController::class)
    ->only(['store', 'update', 'destroy'])
    ->middleware('auth');

Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function (){
    Route::resource('news', \App\Http\Controllers\Admin\NewsController::class)
        ->only('index', 'update');

    Route::resource('comments', \App\Http\Controllers\Admin\CommentsController::class)
        ->only('index', 'update');
});

Auth::routes();

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Comment extends Model
{
    use HasFactory;

    protected $fillable = [
        'message',
        'user_id',
        'news_id',
        'is_approve',
    ];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsTo
     */
    public function news(): BelongsTo
    {
        return $this->belongsTo(News::class);
    }
}

app/Http/Controllers/Admin/CommentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $comments = Comment::orderBy('updated_at', 'desc')->paginate(15);

        return view('admin.comment.index', compact('comments'));
    }

    /**
     * @param Request $request
     * @param Comment $comment
     * @return RedirectResponse
     */
    public function update(Request $request, Comment $comment): RedirectResponse
    {
        if ($request->has('is_approve')) {
            $comment->is_approve ? $comment->is_approve = false : $comment->is_approve = true;
            $comment->save();
            return redirect()->back();
        }

        return redirect()->back();
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CommentRequest;
use App\Models\Comment;
use App\Models\News;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\RedirectResponse;

class CommentsController extends Controller
{
    /**
     * @param News $news
     * @param CommentRequest $request
     * @return RedirectResponse
     */
    public function store(News $news, CommentRequest $request): RedirectResponse
    {
        $data = $request->validated();
        $data['user_id'] = auth()->user()->id;
        $data['news_id'] = $news->id;

        Comment::create($data);

        return redirect()->back();
    }

    /**
     * @param News $news
     * @param Comment $comment
     * @param CommentRequest $request
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(News $news, Comment $comment, CommentRequest $request): RedirectResponse
    {
        $this->authorize('update', $comment);
        $data = $request->validated();
        $comment->update($data);
        $comment->is_approve = false;
        $comment->save();

        return redirect()->back();
    }

    /**
     * @param News $news
     * @param Comment $comment
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(News $news, Comment $comment): RedirectResponse
    {
        $this->authorize('delete', $comment);
        $comment->delete();
        return redirect()->back();
    }
}

resources/views/admin/comment/index.blade.php
@extends('layouts.app')

@section('content')
    <h3>Все Комменты</h3>
    <div class="table-responsive overflow-scroll">
        <table class="table table-striped table-hover table-sm">
            <thead>
            <tr>
                <th scope="col">Коммент</th>
                <th scope="col">Новость</th>
                <th scope="col">Пользователь</th>
                <th scope="col" class="text-end">Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($comments as $comment)
                <tr class="align-middle">
                    <td>{{ $comment->message }}</td>
                    <td><a href="{{ route('news.show', $comment->news) }}">{{ $comment->news->title }}</a></td>
                    <td>{{ $comment->user->name }}</td>
                    <td class="text-end">
                        <div class="btn-group" role="group">
                            <form action="{{route('admin.comments.update', $comment)}}" method="POST">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="is_approve">
                                @if($comment->is_approve)
                                    <button class="btn btn-sm btn-success" type="submit">Снять подтверждение</button>
                                @else
                                    <button class="btn btn-sm btn-outline-success" type="submit">Подтвердить</button>
                                @endif
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div class="row justify-content-md-center p-5">
        <div class="col-md-auto">
            {{ $comments->withQueryString()->links('pagination::bootstrap-4') }}
        </div>
    </div>
@endsection