routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', [\App\Http\Controllers\NewsController::class, 'index']);

Route::resource('news', \App\Http\Controllers\NewsController::class);

Route::post('ratings', [\App\Http\Controllers\RatingController::class, 'store'])
    ->name('rating.store')
    ->middleware('auth');

Route::resource('news.comments', \App\Http\Controllers\CommentsController::class)
    ->only(['store', 'update', 'destroy'])
    ->middleware('auth');

Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function (){
    Route::resource('news', \App\Http\Controllers\Admin\NewsController::class)
        ->only('index', 'update');

    Route::resource('comments', \App\Http\Controllers\Admin\CommentsController::class)
        ->only('index', 'update');
});

Auth::routes();

app/Models/News.php
<?php

namespace App\Models;

use App\Filters\QueryFilter;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class News extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'body',
        'published_at',
        'user_id',
        'category_id',
    ];

    protected $dates = [
        'published_at',
    ];

    /**
     * @return BelongsToMany
     */
    public function tags(): BelongsToMany
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return HasMany
     */
    public function ratings(): HasMany
    {
        return $this->hasMany(Rating::class);
    }

    /**
     * @param Builder $builder
     * @param QueryFilter $filter
     * @return Builder
     */
    public function scopeFilter(Builder $builder, QueryFilter $filter): Builder
    {
        return $filter->apply($builder);
    }
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\News;
use Carbon\Carbon;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class NewsController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $allNews = News::orderBy('updated_at', 'desc')->paginate(15);

        return view('admin.news.index', compact('allNews'));
    }

    /**
     * @param Request $request
     * @param News $news
     * @return RedirectResponse
     */
    public function update(Request $request, News $news): RedirectResponse
    {
        $request->validate([
            'published_at' => 'nullable|date'
        ]);

        if ($request->has('published_at')) {
            is_null($news->published_at) ? $news->published_at = $request->input('published_at') : $news->published_at = null;
            $news->save();
            return redirect()->back();
        }

        return redirect()->route('admin.news.index');
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Filters\NewsFilter;
use App\Http\Requests\NewsRequest;
use App\Models\Category;
use App\Models\News;
use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class NewsController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index(NewsFilter $filter)
    {
        $this->validate($filter->request, [
            'tag_id' => ['int', 'exists:tags,id'],
            'category_id' => ['int', 'exists:categories,id']
        ]);

        $approveNews = News::filter($filter)->where('published_at', '<', Carbon::now())->orderBy('published_at', 'desc')->paginate(9);
        $tags = Tag::all();
        $categories = Category::all();
        return view('news.index', compact('approveNews', 'tags', 'categories'));
    }

    /**
     * @return Application|Factory|View
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', News::class);
        $categories = Category::all();
        $tags = Tag::all();
        return view('news.create', compact('categories', 'tags'));
    }

    /**
     * @param NewsRequest $request
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function store(NewsRequest $request): RedirectResponse
    {
        $this->authorize('create', News::class);
        $news = new News($request->validated());
        $news->save();
        if ($request->has('tags')) {
            $news->tags()->attach($request->input('tags'));
        }

        return redirect()->route('news.index');
    }

    /**
     * @param News $news
     * @return Application|Factory|View
     * @throws AuthorizationException
     */
    public function show(News $news)
    {
        $this->authorize('view', $news);

        $comments = $news->comments()->where('is_approve', true)->orderByDesc('updated_at')->paginate(5);
        return view('news.show', compact('news', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param News $news
     * @return Application|Factory|View
     * @throws AuthorizationException
     */
    public function edit(News $news)
    {
        $this->authorize('update', $news);

        $categories = Category::all();
        $tags = Tag::all();
        return view('news.edit', compact('news','categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param NewsRequest $request
     * @param News $news
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(NewsRequest $request, News $news): RedirectResponse
    {
        $this->authorize('update', $news);

        $news->update($request->validated());
        $news->tags()->detach();
        if ($request->has('tags'))
        {
            $news->tags()->attach($request->input('tags_id'));
        }

        return redirect()->route('news.show', $news);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param News $news
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(News $news): RedirectResponse
    {
        $this->authorize('delete', $news);
        $news->delete();
        return redirect()->back();
    }
}

resources/views/admin/news/index.blade.php
@extends('layouts.app')

@section('content')
    <h3>Все Новости</h3>
    <div class="table-responsive overflow-scroll">
        <table class="table table-striped table-hover table-sm">
            <thead>
            <tr>
                <th scope="col">Новость</th>
                <th scope="col">Дата создания</th>
                <th scope="col">Дата публикации</th>
                <th scope="col" class="text-end">Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($allNews as $news)
                <tr class="align-middle">
                    <td>{{ $news->title }}</td>
                    <td>{{ $news->created_at }}</td>
                    <td>{{is_null($news->published_at) ? 'Не опубликован' : $news->published_at}}</td>
                    <td class="text-end">
                        <div class="btn-group">
                            <div>
                                <a href="{{ route('news.edit', $news) }}" type="button"
                                   class="btn btn-sm btn-outline-info">Изменить</a>
                            </div>

                            <form action="{{ route('admin.news.update', $news) }}" method="post">
                                @method('PUT')
                                @csrf
                                @if(!is_null($news->published_at))
                                    <input type="hidden" name="published_at">
                                    <button class="btn btn-sm btn-success" type="submit">Снять с публикации</button>
                                @else
                                    <a class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target="#exampleModal">Опубликовать
                                    </a>
                                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Дата Публикации</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <input class="form-control" name="published_at" type="datetime-local"/>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                                                    <button type="submit" class="btn btn-primary">Сохранить</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endif
                            </form>
                            <form action="{{ route('news.destroy', $news) }}" method="post">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-sm btn-outline-danger" type="submit">Удалить</button>
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div class="row justify-content-md-center p-5">
        <div class="col-md-auto">
            {{ $allNews->withQueryString()->links('pagination::bootstrap-4') }}
        </div>
    </div>
@endsection