routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', [\App\Http\Controllers\NewsController::class, 'index']);

Route::resource('news', \App\Http\Controllers\NewsController::class);

Route::post('ratings', [\App\Http\Controllers\RatingController::class, 'store'])
    ->name('rating.store')
    ->middleware('auth');

Route::resource('news.comments', \App\Http\Controllers\CommentsController::class)
    ->only(['store', 'update', 'destroy'])
    ->middleware('auth');

Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function (){
    Route::resource('news', \App\Http\Controllers\Admin\NewsController::class)
        ->only('index', 'update');

    Route::resource('comments', \App\Http\Controllers\Admin\CommentsController::class)
        ->only('index', 'update');
});

Auth::routes();

app/Models/News.php
<?php

namespace App\Models;

use App\Filters\QueryFilter;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class News extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'body',
        'published_at',
        'user_id',
        'category_id',
    ];

    protected $dates = [
        'published_at',
    ];

    /**
     * @return BelongsToMany
     */
    public function tags(): BelongsToMany
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return HasMany
     */
    public function ratings(): HasMany
    {
        return $this->hasMany(Rating::class);
    }

    /**
     * @param Builder $builder
     * @param QueryFilter $filter
     * @return Builder
     */
    public function scopeFilter(Builder $builder, QueryFilter $filter): Builder
    {
        return $filter->apply($builder);
    }
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\News;
use Carbon\Carbon;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class NewsController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $allNews = News::orderBy('updated_at', 'desc')->paginate(15);

        return view('admin.news.index', compact('allNews'));
    }

    /**
     * @param Request $request
     * @param News $news
     * @return RedirectResponse
     */
    public function update(Request $request, News $news): RedirectResponse
    {
        $request->validate([
            'published_at' => 'nullable|date'
        ]);

        if ($request->has('published_at')) {
            is_null($news->published_at) ? $news->published_at = $request->input('published_at') : $news->published_at = null;
            $news->save();
            return redirect()->back();
        }

        return redirect()->route('admin.news.index');
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Filters\NewsFilter;
use App\Http\Requests\NewsRequest;
use App\Models\Category;
use App\Models\News;
use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class NewsController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index(NewsFilter $filter)
    {
        $this->validate($filter->request, [
            'tag_id' => ['int', 'exists:tags,id'],
            'category_id' => ['int', 'exists:categories,id']
        ]);

        $approveNews = News::filter($filter)->where('published_at', '<', Carbon::now())->orderBy('published_at', 'desc')->paginate(9);
        $tags = Tag::all();
        $categories = Category::all();
        return view('news.index', compact('approveNews', 'tags', 'categories'));
    }

    /**
     * @return Application|Factory|View
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', News::class);
        $categories = Category::all();
        $tags = Tag::all();
        return view('news.create', compact('categories', 'tags'));
    }

    /**
     * @param NewsRequest $request
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function store(NewsRequest $request): RedirectResponse
    {
        $this->authorize('create', News::class);
        $news = new News($request->validated());
        $news->save();
        if ($request->has('tags')) {
            $news->tags()->attach($request->input('tags'));
        }

        return redirect()->route('news.index');
    }

    /**
     * @param News $news
     * @return Application|Factory|View
     * @throws AuthorizationException
     */
    public function show(News $news)
    {
        $this->authorize('view', $news);

        $comments = $news->comments()->where('is_approve', true)->orderByDesc('updated_at')->paginate(5);
        return view('news.show', compact('news', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param News $news
     * @return Application|Factory|View
     * @throws AuthorizationException
     */
    public function edit(News $news)
    {
        $this->authorize('update', $news);

        $categories = Category::all();
        $tags = Tag::all();
        return view('news.edit', compact('news','categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param NewsRequest $request
     * @param News $news
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(NewsRequest $request, News $news): RedirectResponse
    {
        $this->authorize('update', $news);

        $news->update($request->validated());
        $news->tags()->detach();
        if ($request->has('tags'))
        {
            $news->tags()->attach($request->input('tags_id'));
        }

        return redirect()->route('news.show', $news);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param News $news
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(News $news): RedirectResponse
    {
        $this->authorize('delete', $news);
        $news->delete();
        return redirect()->back();
    }
}

resources/views/news/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col main pt-5 mt-3">
        <h1>Создать новую новость</h1>
        <form method="post" action="{{ route('news.store') }}">
            @csrf
            <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
            <div class="form-group">
                <label for="title"><b>Фамилия, имя</b></label>
                <input placeholder="Введите заголовок" autofocus type="text" class="form-control" id="title"
                       name="title">
                @error('title')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group mt-3">
                <label for="floatingTextarea2"><b>Новость</b></label>
                <div class="form-floating">
                    <textarea class="form-control" name="body" id="floatingTextarea2" style="height: 100px"></textarea>
                </div>
                @error('body')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group mt-3">
                <label for="categories"><b>Категории</b></label>
            <select name="category_id" id="categories" class="form-select" aria-label="Default select example">
                @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
            </select>
            </div>
            <p>
                <a class="btn btn-outline-info dropdown-toggle mt-3" data-bs-toggle="collapse" href="#tags"
                   role="button" aria-expanded="false" aria-controls="collapseExample">
                    Теги
                </a>
            </p>
            <div class="collapse" id="tags">
                <div class="card card-body">
                    @foreach($tags as $tag)
                        <div class="form-check">
                            <input class="form-check-input" name="tags[]" type="checkbox"
                                   value=" {{ $tag->id }} " id="tags{{$tag->id}}">
                            <label class="form-check-label" for="tags{{$tag->id}}">
                                {{$tag->name}}
                            </label>
                        </div>
                    @endforeach
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-4">Сохранить</button>
        </form>
    </div>
@endsection

resources/views/news/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="col main pt-5 mt-3">
        <h1>Редактировать новость</h1>
        <form method="post" action="{{ route('news.update', $news) }}">
            @method('PUT')
            @csrf
            <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
            <div class="form-group">
                <label for="title"><b>Фамилия, имя</b></label>
                <input placeholder="Введите заголовок" autofocus type="text" class="form-control" id="title"
                       name="title" value="{{ $news->title }}">
                @error('title')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group mt-3">
                <label for="floatingTextarea2"><b>Новость</b></label>
                <div class="form-floating">
                    <textarea class="form-control" name="body" id="floatingTextarea2"
                              style="height: 100px">{{ $news->body }}</textarea>
                </div>
                @error('body')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group mt-3">
                <label for="categories"><b>Категории</b></label>
                <select name="category_id" id="categories" class="form-select" aria-label="Default select example">
                    @foreach($categories as $category)
                        <option @if($category->id == $news->category->id) selected
                                @endif value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
            </div>
            <p>
                <a class="btn btn-outline-info dropdown-toggle mt-3" data-bs-toggle="collapse" href="#tags"
                   role="button" aria-expanded="false" aria-controls="collapseExample">
                    Теги
                </a>
            </p>
            <div class="collapse" id="tags">
                <div class="card card-body">
                    @foreach($tags as $tag)
                        <div class="form-check">
                            <input class="form-check-input" name="tags[]" type="checkbox"
                                   value="{{ $tag->id }}" id="tags{{$tag->id}}"
                                   @if (count($news->tags->where('id', $tag->id)))
                                   checked
                                @endif>
                            <label class="form-check-label" for="tags{{$tag->id}}">
                                {{$tag->name}}
                            </label>
                        </div>
                    @endforeach
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-4">Сохранить</button>
        </form>
    </div>
@endsection

resources/views/news/index.blade.php
@extends('layouts.app')
@section('content')
    @if(Auth::user() && Auth::user()->is_admin)
        <a href="{{ route('admin.news.index') }}" class="btn btn-success mb-5">АДМИНКА</a>
        <a href="{{ route('news.create') }}" class="btn btn-outline-info mb-5">Добавить новость</a>
    @endif
    <div class="mb-5">
        <form id="form_id" action="{{ route('news.index') }}" method="GET">
            <h5>Фильтрация по тегам</h5>
            <select name="tag_id" class="form-select" aria-label="Default select example" onchange="this.form.submit()">
                <option selected disabled>Отфильтровать по тегам:</option>
                @foreach($tags as $tag)
                    <option @if(isset($_GET['tag_id'])) @if($_GET['tag_id'] == $tag->id)
                            selected @endif @endif value="{{$tag->id}}">{{$tag->name}}</option>
                @endforeach
            </select>
        </form>
    </div>

    <div class="mb-5">
        <form id="category_id" action="{{ route('news.index') }}" method="GET">
            <h5>Фильтрация по категориям</h5>
            <select name="category_id" class="form-select" aria-label="Default select example"
                    onchange="this.form.submit()">
                <option selected disabled>Отфильтровать по категориям:</option>
                @foreach($categories as $category)
                    <option @if(isset($_GET['category_id'])) @if($_GET['category_id'] == $category->id)
                            selected @endif @endif value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
            </select>
        </form>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach($approveNews as $news)
            <div class="col mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{{ route('news.show', $news) }}">{{ $news->title }}</a></h5>
                        <p class="card-text">{{ $news->body }}</p>
                        <div class="col-sm-12 col-md-8 col-lg-8">
                            @if($news->tags->isNotEmpty())
                                <div class="text-secondary mt-3 text-uppercase">
                                    <strong>ТЕГИ</strong>
                                </div>
                                @foreach($news->tags as $tag)
                                    <div class="badge border border-info shadow text-uppercase btn-outline-info">
                                        <a href="#" class="text-dark text-decoration-none">{{ $tag->name }}</a>
                                    </div>
                                @endforeach
                            @endif
                            @if(isset($news->category))
                                <div class="text-secondary mt-3 text-uppercase">
                                    <strong>КАТЕГОРИЯ</strong>
                                </div>
                                <div class="badge border border-info shadow text-uppercase btn-outline-info">
                                    <a href="#" class="text-dark text-decoration-none">{{ $news->category->name }}</a>
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">
                            <strong>Дата публикации:</strong> {{ $news->published_at->diffForHumans() }}
                        </small>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    <div class="row justify-content-md-center p-5">
        <div class="col-md-auto">
            {{ $approveNews->withQueryString()->links('pagination::bootstrap-4') }}
        </div>
    </div>
@endsection

resources/views/news/show.blade.php
@extends('layouts.app')
@section('content')
    @can('delete', $news)
        <a href="{{ route('news.edit', $news) }}" class="btn btn-outline-info mb-2">Редактировать</a>
        <form action="{{ route('news.destroy', $news) }}" method="POST">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-outline-danger">Удалить</button>
        </form>
    @endcan
    <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-2">
        <div class="col col-sm-12 col-md-6 col-lg-4 row border-dark border-1 p-1">
            <div class="col-sm-12 col-md-8 col-lg-8">
                <h3>{{ $news->title }}</h3>
                @if(isset($news->category))
                    <div class="text-secondary text-uppercase">
                        <strong>Категория</strong>
                    </div>
                    <div class="badge border border-info shadow text-uppercase btn-outline-info">
                        <span class="text-dark">{{ $news->category->name }}</span>
                    </div>
                @endif

                @if($news->tags->isNotEmpty())
                    <div class="text-secondary mt-3 text-uppercase">
                        <strong>Теги</strong>
                    </div>
                    @foreach($news->tags as $tag)
                        <div class="badge border border-info shadow text-uppercase btn-outline-info">
                            <span class="text-dark">{{ $tag->name }}</span>
                        </div>
                    @endforeach
                @endif

                <div class="text-secondary mt-3 text-uppercase">
                    <strong>Автор</strong>
                </div>
                <div class="badge border border-info shadow text-uppercase btn-outline-info">
                    <span class="text-dark">{{ $news->user->name }}</span>
                </div>

                <div class="text-secondary mt-3 text-uppercase">
                    <strong>Дата создания</strong>
                </div>
                <div class="badge border border-info shadow text-uppercase btn-outline-info">
                    <span class="text-dark">{{ $news->created_at }}</span>
                </div>

                <div class="text-secondary mt-3 text-uppercase">
                    <strong>Дата публикации</strong>
                </div>
                <div class="badge border mb-3 border-info shadow text-uppercase btn-outline-info">
                    <span class="text-dark">{{ $news->published_at }}</span>
                </div>


                <form action="{{ route('rating.store') }}" method="POST">
                    @csrf
                    <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
                    <input type="hidden" name="news_id" value="{{ $news->id }}">
                    <h4>Оценить новость</h4>
                    <p class="m-0">По качеству</p>
                    <div class="form-check">
                        <input class="form-check-input" value="1" type="radio" name="quality" id="quality1" checked>
                        <label class="form-check-label" for="quality1">
                            Качественно
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" value="0" type="radio" name="quality" id="quality2">
                        <label class="form-check-label" for="quality2">
                            Некачественно
                        </label>
                    </div>

                    <hr>
                    <p class="m-0">По актуальности</p>
                    <div class="form-check">
                        <input class="form-check-input" value="1" type="radio" name="actual" id="actual1" checked>
                        <label class="form-check-label" for="actual1">
                            Актуально
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" value="0" type="radio" name="actual" id="actual0">
                        <label class="form-check-label" for="actual0">
                            Не Актуально
                        </label>
                    </div>

                    <hr>
                    <p class="m-0">По довольности</p>
                    <div class="form-check">
                        <input class="form-check-input" value="1" type="radio" name="happy" id="happy1" checked>
                        <label class="form-check-label" for="happy1">
                            Доволен
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" value="0" type="radio" name="happy" id="happy2">
                        <label class="form-check-label" for="happy2">
                            Не Доволен
                        </label>
                    </div>
                    <button type="submit" class="btn btn-outline-info fw-bold shadow-lg">Оценить</button>
                </form>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-8 border-dark p-1 border-1">
            <div>
                <h4>Текст новости</h4>
                <p>{{ $news->body }}</p>
            </div>
        </div>
    </div>

    @if($comments->count() > 0)
        <div class="list-group">
            <h3 class="my-3">Количество комментариев: {{ $comments->count() }}</h3>
            @foreach($comments as $comment)
                <div class="list-group-item list-group-item-action shadow-lg">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="w-75">
                            <h5 class="mb-1">
                                <a href="" class="text-decoration-none">{{ $comment->user->name }}</a>
                            </h5>
                            <p class="mb-1"><em>{{ $comment->message }}</em></p>
                            <div class="accordion accordion-flush" id="accordionFlushExample">
                                <div class="accordion-item">
                                    <div id="flush-collapse{{ $comment->id }}" class="accordion-collapse collapse"
                                         aria-labelledby="flush-heading"
                                         data-bs-parent="#accordionFlushExample">
                                        <div class="accordion-body">
                                            @can('delete', $comment)
                                                <form
                                                    action="{{ route('news.comments.update', ['news' => $news, 'comment' => $comment]) }}"
                                                    method="POST">
                                                    @csrf
                                                    @method('PUT')
                                                    <div class="row">
                                                        <div class="input-group">
                                                        <textarea class="form-control border-info"
                                                                  name="message"
                                                                  aria-label="With textarea"
                                                                  cols="30" rows="5"
                                                        >{{ $comment->message }}</textarea>
                                                        </div>
                                                    </div>
                                                    <div class="row mt-2 mb-5">
                                                        <div class="col-12">
                                                            <button type="submit"
                                                                    class="btn btn-outline-info">Редактировать
                                                            </button>
                                                        </div>
                                                    </div>
                                                </form>
                                            @endcan
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <small class="text-muted">{{ $comment->updated_at->diffForHumans() }}</small>
                            @can('delete', $comment)
                                <form
                                    action="{{ route('news.comments.destroy', ['news' => $news, 'comment' => $comment]) }}"
                                    method="POST" class="text-end">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-outline-info btn-sm" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#flush-collapse{{ $comment->id }}" aria-expanded="false"
                                            aria-controls="flush-collapse{{ $comment->id }}">
                                        Редактировать
                                    </button>
                                    <button type="submit" class="btn btn-outline-danger btn-sm">
                                        Удалить
                                    </button>
                                </form>
                            @endcan
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="row justify-content-md-center mt-5">
            <div class="col-md-auto">
                {{ $comments->withQueryString()->links('pagination::bootstrap-4') }}
            </div>
        </div>
    @endif

    @auth()
        <div>
            <h3 class="mt-5 mb-3">Добавить коммент</h3>
            <form action="{{ route('news.comments.store', $news) }}" method="POST">
                @csrf
                <div class="row">
                    <div class="input-group">
                            <textarea
                                class="form-control border-info @error('message') is-invalid border-danger @enderror"
                                name="message" aria-label="With textarea"
                                cols="30" rows="5" placeholder="Напишите коммент"></textarea>
                    </div>
                    @error('message')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="row mt-2 mb-5">
                    <div class="col-12">
                        <button type="submit" class="btn btn-outline-info">Добавить</button>
                    </div>
                </div>
            </form>
        </div>
    @endauth
    @guest()
        <h4><a class="btn btn-outline-success"
               href="{{ route('login') }}">Войти</a> Что бы оставить комментарий</h4>
    @endguest

    <a href="{{route('news.index')}}" class="btn btn-outline-info">@lang('messages.go_back')</a>
@endsection